# Generated by Django 3.0.6 on 2020-05-19 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='order',
            field=models.SmallIntegerField(default=0, unique=True),
        ),
    ]
