# Generated by Django 3.0.6 on 2020-05-19 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_image_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['order']},
        ),
    ]
